### ISSUE TITLE
NodeConf logos

### ISSUE THREAD

**Issue by thefoxis** [nodeconf/resources#1]
@mikeal&mdash;can you push NodeConf logos in vector formats? (AI, EPS, SVG, whatever you have)

**Comment by mikeal** [comment]
@jlord @kriesse what do we have from prior years around?

**Comment by thefoxis** [comment]
I think for the upcoming one we just need main NodeConf logo from 2013 :)

**Comment by jlord** [comment]
![nodeconf2013](https://cloud.githubusercontent.com/assets/1305617/5636132/35f8cd66-95a4-11e4-89be-f731dd2f2de7.png)

This one?

**Comment by jlord** [comment]
I'll just make a PR with what I have :+1:

**Comment by thefoxis** [comment]
Aaaaand done :)
